# (optional) Add name prefix to all resources provided by chart
resourcePrefix: ''

# Disable role and rolebinding for jenkins pipeline
features:
  role:
    enabled: false
  secret:
    enabled: false

connect:
  # Connect cluster name
  name: debezium-kafka-connect-cluster

  # Connect cluster image
  image: <registry>/<namespace>/debezium-connector-mongodb:3.0.8

  # Connect cluster version
  version: 3.5.0

  # Connect cluster istances
  replicas: 1

  # Connect cluster annotations
  annotations:
    app: cdc-debezium

  # Connect cluster labels
  labels:
    app: cdc-debezium

  # Topic and group.id prefix
  configPrefix: cdc.debezium.acme

  # Kafka cluster bootstrap servers
  bootstrapServers: 
    - <bootstrap_server1>

  # Kafka cluster CA certificates
  tls:
    trustedCertificates:
      - name: ca1
        ca: |
          -----BEGIN CERTIFICATE-----
          CERTIFICATE
          -----END CERTIFICATE-----

  # Kafka cluster authentication
  authentication:
    username: <kafka_user>
    password: <kafka_pwd>

  # Connect cluster default resources
  resources:
    requests:
      cpu: "1"
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 1Gi

  # Connect cluster default logging
  logging:
    loggers:
      connect.root.logger.level: "INFO"

  # Connect cluster image pull secrets
  imagePullSecrets:
    - <image_pull_secret>

connector:
  # Enable connector
  enabled: true

  # Connector name
  name: debezium-mongodb-connector

  # Connector class
  class: io.debezium.connector.mongodb.MongoDbConnector

  # Connector max tasks
  tasksMax: 1

  # Database credentials
  database:
    user: <db_user>
    password: <db_pwd>

  # Connector configs
  config:
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: 'false'
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: 'false'

    # For details see. https://docs.redhat.com/en/documentation/red_hat_build_of_debezium/2.5.4/html/debezium_user_guide/debezium-connector-for-mongodb#mongodb-connector-properties
    mongodb.authsource: <auth_db>
    database.include.list: <db>
    database.dbname: <db>
    collection.include.list: "<db>.<collection1>"
    field.exclude.list: <db>.*._class
  
  # Topic creation configs
  topic_groups:
    default:
      partitions: 5
      replication.factor: '3'
      retention.ms: '604800000'
      cleanup.policy: delete
