{{- if .Values.features.secret.enabled }}
{{- if .Values.connect.authentication }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "debezium-connect.resourcePrefix" . }}debezium-connect-credential'
  labels:
    {{- include "debezium-connect.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.connect.authentication.password }}
{{- end }}
{{- end }}