{{- if .Values.features.secret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "debezium-connect.resourcePrefix" . }}debezium-connector-db-credential'
  labels:
    {{- include "debezium-connect.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.connector.database.user }}
  password: {{ .Values.connector.database.password }}
{{- end }}
