---
{{- if .Values.connect.tls }}
apiVersion: v1
kind: Secret
metadata:
  name: debezium-connect-tls-certs
  labels:
    {{- include "debezium-connect.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.connect.tls.ca | b64enc }}
---
{{- end }}
{{- if .Values.connect.authentication }}
apiVersion: v1
kind: Secret
metadata:
  name: debezium-connect-scram-credential
  labels:
    {{- include "debezium-connect.labels" . | nindent 4 }}
type: Opaque
data:
  scram-sha-512-password: {{ .Values.connect.authentication.password | b64enc }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: debezium-connector-db-credential
  labels:
    {{- include "debezium-connect.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.connector.database.user | b64enc }}
  password: {{ .Values.connector.database.password | b64enc }}