{{- if .Values.features.role.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: '{{ include "debezium-connect.resourcePrefix" . }}debezium-connector-configuration-role'
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: 
    - '{{ include "debezium-connect.resourcePrefix" . }}debezium-connector-db-credential'
    - '{{ include "debezium-connect.resourcePrefix" . }}debezium-connect-credential'
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: '{{ include "debezium-connect.resourcePrefix" . }}debezium-connector-configuration-role-binding'
subjects:
- kind: ServiceAccount
  name: '{{ include "debezium-connect.resourcePrefix" . }}{{ .Values.connect.name }}-connect'
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: '{{ include "debezium-connect.resourcePrefix" . }}debezium-connector-configuration-role'
  apiGroup: rbac.authorization.k8s.io
{{- end }}