{{- if .Values.features.secret.enabled }}
{{- if .Values.connect.tls }}
{{- range $trustedCertifcate := .Values.connect.tls.trustedCertificates }}
---
apiVersion: v1
kind: Secret
metadata:
  name: '{{ include "debezium-connect.resourcePrefix" $ }}debezium-connect-tls-{{ $trustedCertifcate.name }}'
  labels:
    {{- include "debezium-connect.labels" $ | nindent 4 }}
type: Opaque
stringData:
  ca.crt: | 
    {{- $trustedCertifcate.ca | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}
